### ISSUE TITLE
Avoid conflicts in pull request

### ISSUE THREAD

**Issue by mejt** [adrianpietka/larmo#75]
We need to avoid conflicts caused minify JS and CSS files.

**Comment by dalailomo** [comment]
What about adding those files to `.gitignore`?

**Comment by zeulus** [comment]
Make sure then that you have added instruction to webapp README.md about required css/js compilation before deployment. But for someone who just want to use that and deploy on heroku it's not a good deal if that person has to compile assets before deployment. Maybe creating intermediate branch for webapp or moving it to separated repo would be better ideas?

**Comment by mejt** [comment]
Today I was reading about workflow with grunt and minify files and I have conclusion:
**Generated files by grunt shouldn't add to repository**

I opened pull request #77  with my changes:
- At the moment all things are "heroku-friendly" and grunt compile assets in deployment process. All is automated thanks package.json file.
- Person who clone repository needs to install all node dependencies via command ```npm install``` and additionally this command should compile all dev assets.
- Start development with command ```grunt``` (this command should precompile all assets and start watching changes).

This workflow is better and painless.

But this process can be more effective. When we move this WebApp to separate repo then we'll add auto deploying via Travis CI. (For example -> each merge to master will trigger tests in Travis CI and deploying to server).
