### ISSUE TITLE
Add script for loading data with scrolling

### ISSUE THREAD

**Issue by mejt** [adrianpietka/larmo#84]
Like this script: https://github.com/sroze/ngInfiniteScroll

**Comment by mejt** [comment]
I added this script to our web and view is available at http://larmo.herokuapp.com/
@adrianpietka what do you think about it?

**Comment by zeulus** [comment]
That would be good to have some spinner or loading message, at least at
mobile version there's none.
28 lip 2015 16:00 "Mateusz Książek" <notifications@github.com> napisał(a):

**Comment by mejt** [comment]
Hi @zeulus, done. I added spinner. Good for you? :)
